config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/' => 'index#index'
  resources :index, only: [:index, :show, :edit, :update, :destory] do
    member do
      patch :update_profile_image
      post :update_profile_image
      get :articles
      get :rooms
      get :chat
      post :post_message
    end
    get '/change_sakura/:id', on: :collection, action: :change_sakura
  end

  resources :sakura, only: [:index] do
  end

  resources :article, only: [:index, :new, :create, :show, :edit, :update, :destory]
  resources :room, only: [:index, :show]
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">
    Anything you want
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2014-<%= Date.today.year %> <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

app/views/layouts/_navbar.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>

  <!-- SEARCH FORM -->
  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-address-card"></i>
        <span id="select_user_nickname">
          <%= $sakura[:nickname]  if $sakura.present? %>
          <%= "クリックしてユーザーを選択してください" if $sakura.nil? %>
        </span>
        <!-- <span class="badge badge-danger navbar-badge">3</span> -->
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <% $sakuras.each do |user| %>
          <a data-id="<%= user[:documentId] %>" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <% if user[:profile_image_url].present? %>
                <img src="<%= user[:profile_image_url] %>" class="img-size-50 mr-3 img-circle">
              <% else %>
                <%= image_tag 'user_profile_default_icon/no_avatar.png', class: "img-size-50 mr-3 img-circle" %>
              <% end %>
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  <%= user[:nickname] %><br> ( <%= $prefectures[user[:prefecture_id]] %> )
                </h3>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
        <% end %>
      </div>
    </li>

    <script>
    $(function () {
      // ユーザー切り替え
      $('.dropdown-item').click(function() {
          $.ajax({
            url: '/index/change_sakura/' + $(this).attr('data-id'),
            dataType: 'json',
            type: 'GET',
            cache: true,
            success: function(data) {
              console.log(data)
              location.href = location.href
            },
            error: function(XMLHttpRequest, textStatus, errorThrown) {
              //response(['']);
            }
          });
      })
    });
    </script>

    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
    </li>
    <li class="nav-item">
    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/layouts/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <%= link_to index_index_path, class:"brand-link" do %>
    <img src="<%= image_path 'AdminLTELogo.png' %>" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
         style="opacity: .8">
    <span class="brand-text font-weight-light">MENU</span>
  <% end %>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->

    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="info bg-gray-dark">
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->

        <li class="nav-item">
          <%= link_to index_index_path, class:"nav-link" do %>
            <i class="nav-icon fas fa-th"></i>
            <p>
              ユーザー
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to sakura_index_path, class:"nav-link" do %>
            <i class="nav-icon fas fa-th"></i>
            <p>
              さくら
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to article_index_path, class:"nav-link" do %>
            <i class="nav-icon fas fa-th"></i>
            <p>
              投稿
            </p>
          <% end %>
        </li>
        <% if $sakura.present? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= url_for("/index/#{$sakura[:documentId]}/rooms") %>">
              <i class="nav-icon fas fa-th"></i>
              <p>
              <%= $sakura[:nickname] %>
              </p>
            </a>
          </li>
        <% end %>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

<script>
$(function () {
var url = window.location;
//console.log(url);
$('ul.nav-sidebar a').filter(function() {
  return this.href == url || url.href.indexOf(this.href) == 0;
}).addClass('active');

$('ul.nav-sidebar a').filter(function() {
  return this.href == url || url.href.indexOf(this.href) == 0;
}).parent().parent().parent().addClass('menu-open');
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminL P-Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  </head>

  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <!-- Navbar -->
      <%= render 'layouts/navbar' %>
      <!-- /.navbar -->

      <!-- Main Sidebar Container -->
      <%= render 'layouts/sidebar' %>
      <!-- / Main Sidebar Container -->

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <%= yield %>
        <%= toastr_flash %>
      </div>
      <!-- /.content-wrapper -->

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
        <div class="p-3">
          <h5>Title</h5>
          <p>Sidebar content</p>
        </div>
      </aside>
      <!-- /.control-sidebar -->

      <!-- Main Footer -->
      <%= render 'layouts/footer' %>
      <!-- / Main Footer -->

    </div>
    <!-- ./wrapper -->

<script>
$(function () {
  $('tbody tr[data-href]').addClass('clickable').click( function() {
    url = $(this).attr('data-href');
    window.open(url, '_blank');
  }).find('a').hover( function() {
      $(this).parents('tr').unbind('click');
  }, function() {
      $(this).parents('tr').click( function() {
          url = $(this).attr('data-href');
          window.open(url, '_blank');
      });
  });
});
</script>
</html>